/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aydinsandikcimenu;

/**
 *
 * @author aydin
 */
public class AydinSandikciScoreBoard extends javax.swing.JFrame {

    /**
     * Creates new form AydinSandikciScoreBoard
     */
    GameManager gm = new GameManager();
    public AydinSandikciScoreBoard(String isim) {
        initComponents();
        gm.setIsim(isim);
        lblUserName.setText(gm.getIsim());
        BinarySearchTree bst = gm.dosyadanOku();
        lblBestScore.setText(bst.worstScore().puan+"("+bst.bestScore().level+")");
        lblWorstScore.setText(bst.bestScore().puan+"("+bst.worstScore().level+")");
        lblAllScores.setText(bst.inorder());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        lblAllScores = new javax.swing.JLabel();
        lblBestScore = new javax.swing.JLabel();
        lblWorstScore = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 250, 20));

        lblAllScores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAllScores.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblAllScores, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 260, 20));

        lblBestScore.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblBestScore.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblBestScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 240, 20));

        lblWorstScore.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblWorstScore.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblWorstScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 240, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aydinsandikcimenu/scoreboard.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AydinSandikciScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AydinSandikciScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AydinSandikciScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AydinSandikciScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AydinSandikciScoreBoard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAllScores;
    private javax.swing.JLabel lblBestScore;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblWorstScore;
    // End of variables declaration//GEN-END:variables
}
