/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aydinsandikcimenu;

import java.util.LinkedList;
import javax.swing.JLabel;

/**
 *
 * @author aydin
 */
public class AydinSandikciIkinciEtap extends javax.swing.JFrame {

    /**
     * Creates new form AydinSandikciIkinciEtap
     */
    GameManager gm = new GameManager();
    LinkedList h = new LinkedList();

    public AydinSandikciIkinciEtap(String isim) {
        initComponents();
        gm.setIsim(isim);
        gm.setLevel(2);
        System.out.println(isim + gm.getIsim());
        lblISIM.setText(isim);
        lblLEVEL.setText("Level 2");
        lblZAR.setText(gm.getZar() + "");
        lblPUAN.setText(gm.getPuan() + "");
        lblHAZINE.setText(gm.getHazine() + "");
        lblKONUM.setText(gm.getKonum() + "");
        gm.haritaOlustur();
        haritala();
    }
    
    private void haritala() {
        h.add(lbl1);
        h.add(lbl2);
        h.add(lbl3);
        h.add(lbl4);
        h.add(lbl5);
        h.add(lbl6);
        h.add(lbl7);
        h.add(lbl8);
        h.add(lbl9);
        h.add(lbl10);
        h.add(lbl11);
        h.add(lbl12);
        h.add(lbl13);
        h.add(lbl14);
        h.add(lbl15);
        h.add(lbl16);
        h.add(lbl17);
        h.add(lbl18);
        h.add(lbl19);
        h.add(lbl20);
        h.add(lbl21);
        h.add(lbl22);
        h.add(lbl23);
        h.add(lbl24);
        h.add(lbl25);
        h.add(lbl26);
        h.add(lbl27);
        h.add(lbl28);
        h.add(lbl29);
        h.add(lbl30);
        for (int i = 0; i < 30; i++) {
            if (gm.list.get(i) == 0) {
                if (h.get(i) instanceof javax.swing.JLabel) {
                    JLabel lbl = (javax.swing.JLabel) h.get(i);
                    lbl.setText((i + 1) + ". " + "Spot boş");
                }
            } else if (gm.list.get(i) == 1) {
                if (h.get(i) instanceof javax.swing.JLabel) {
                    JLabel lbl = (javax.swing.JLabel) h.get(i);
                    lbl.setText((i + 1) + ". " + " +10 puan");
                }
            } else if (gm.list.get(i) == 2) {
                if (h.get(i) instanceof javax.swing.JLabel) {
                    JLabel lbl = (javax.swing.JLabel) h.get(i);
                    lbl.setText((i + 1) + ". " + " -10 puan");
                }
            } else if (gm.list.get(i) == 3) {
                if (h.get(i) instanceof javax.swing.JLabel) {
                    JLabel lbl = (javax.swing.JLabel) h.get(i);
                    lbl.setText((i + 1) + ". " + " 3 adım ileri");
                }
            } else if (gm.list.get(i) == 4) {
                if (h.get(i) instanceof javax.swing.JLabel) {
                    JLabel lbl = (javax.swing.JLabel) h.get(i);
                    lbl.setText((i + 1) + ". " + " 2 adım geri");
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStart = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        lbl18 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        lbl24 = new javax.swing.JLabel();
        lbl25 = new javax.swing.JLabel();
        lbl26 = new javax.swing.JLabel();
        lbl27 = new javax.swing.JLabel();
        lbl28 = new javax.swing.JLabel();
        lbl29 = new javax.swing.JLabel();
        lbl30 = new javax.swing.JLabel();
        lblBitis = new javax.swing.JLabel();
        lblHazineAvcisi = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblLEVEL = new javax.swing.JLabel();
        lblIsim = new javax.swing.JLabel();
        lblISIM = new javax.swing.JLabel();
        lblZar = new javax.swing.JLabel();
        lblZAR = new javax.swing.JLabel();
        lblPuan = new javax.swing.JLabel();
        lblPUAN = new javax.swing.JLabel();
        lblHazine = new javax.swing.JLabel();
        lblHAZINE = new javax.swing.JLabel();
        lblKonum = new javax.swing.JLabel();
        lblKONUM = new javax.swing.JLabel();
        btnZarAt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl31 = new javax.swing.JLabel();
        lbl32 = new javax.swing.JLabel();
        lbl33 = new javax.swing.JLabel();
        lbl34 = new javax.swing.JLabel();
        lbl35 = new javax.swing.JLabel();
        lbl36 = new javax.swing.JLabel();
        lbl37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStart.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblStart.setForeground(new java.awt.Color(51, 51, 51));
        lblStart.setText("START");
        getContentPane().add(lblStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 100, 60));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("1");
        lbl1.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        lbl2.setBackground(new java.awt.Color(0, 0, 0));
        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("1");
        lbl2.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 0));
        lbl3.setText("1");
        lbl3.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        lbl4.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl4.setForeground(new java.awt.Color(0, 0, 0));
        lbl4.setText("1");
        lbl4.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 60, -1));

        lbl5.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl5.setForeground(new java.awt.Color(0, 0, 0));
        lbl5.setText("1");
        lbl5.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 79, -1));

        lbl6.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl6.setForeground(new java.awt.Color(0, 0, 0));
        lbl6.setText("1");
        lbl6.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        lbl7.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl7.setForeground(new java.awt.Color(0, 0, 0));
        lbl7.setText("1");
        lbl7.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        lbl8.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl8.setForeground(new java.awt.Color(0, 0, 0));
        lbl8.setText("1");
        lbl8.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 80, -1));

        lbl9.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl9.setForeground(new java.awt.Color(0, 0, 0));
        lbl9.setText("1");
        lbl9.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));

        lbl10.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl10.setForeground(new java.awt.Color(0, 0, 0));
        lbl10.setText("1");
        lbl10.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 70, -1));

        lbl11.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl11.setForeground(new java.awt.Color(0, 0, 0));
        lbl11.setText("1");
        lbl11.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 70, 50));

        lbl12.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl12.setForeground(new java.awt.Color(0, 0, 0));
        lbl12.setText("1");
        lbl12.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 80, -1));

        lbl13.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl13.setForeground(new java.awt.Color(0, 0, 0));
        lbl13.setText("1");
        lbl13.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 70, -1));

        lbl14.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl14.setForeground(new java.awt.Color(0, 0, 0));
        lbl14.setText("1");
        lbl14.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 70, 50));

        lbl15.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl15.setForeground(new java.awt.Color(0, 0, 0));
        lbl15.setText("1");
        lbl15.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        lbl16.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl16.setForeground(new java.awt.Color(0, 0, 0));
        lbl16.setText("1");
        lbl16.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 70, 50));

        lbl17.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl17.setForeground(new java.awt.Color(0, 0, 0));
        lbl17.setText("1");
        lbl17.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 80, -1));

        lbl18.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl18.setForeground(new java.awt.Color(0, 0, 0));
        lbl18.setText("1");
        lbl18.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 70, -1));

        lbl19.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl19.setForeground(new java.awt.Color(0, 0, 0));
        lbl19.setText("1");
        lbl19.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 80, -1));

        lbl20.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl20.setForeground(new java.awt.Color(0, 0, 0));
        lbl20.setText("1");
        lbl20.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 90, -1));

        lbl21.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl21.setForeground(new java.awt.Color(0, 0, 0));
        lbl21.setText("1");
        lbl21.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 80, -1));

        lbl22.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl22.setForeground(new java.awt.Color(0, 0, 0));
        lbl22.setText("1");
        lbl22.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 70, -1));

        lbl23.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl23.setForeground(new java.awt.Color(0, 0, 0));
        lbl23.setText("1");
        lbl23.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl23, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 80, -1));

        lbl24.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl24.setForeground(new java.awt.Color(0, 0, 0));
        lbl24.setText("1");
        lbl24.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 80, -1));

        lbl25.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl25.setForeground(new java.awt.Color(0, 0, 0));
        lbl25.setText("1");
        lbl25.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 70, 60));

        lbl26.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl26.setForeground(new java.awt.Color(0, 0, 0));
        lbl26.setText("1");
        lbl26.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 90, -1));

        lbl27.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl27.setForeground(new java.awt.Color(0, 0, 0));
        lbl27.setText("1");
        lbl27.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 100, -1));

        lbl28.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl28.setForeground(new java.awt.Color(0, 0, 0));
        lbl28.setText("1");
        lbl28.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 80, 50));

        lbl29.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl29.setForeground(new java.awt.Color(0, 0, 0));
        lbl29.setText("1");
        lbl29.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl29, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 80, 50));

        lbl30.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        lbl30.setForeground(new java.awt.Color(0, 0, 0));
        lbl30.setText("1");
        lbl30.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 70, -1));

        lblBitis.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblBitis.setForeground(new java.awt.Color(0, 0, 0));
        lblBitis.setText("END");
        getContentPane().add(lblBitis, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 90, 60));

        lblHazineAvcisi.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        lblHazineAvcisi.setForeground(new java.awt.Color(0, 0, 0));
        lblHazineAvcisi.setText("Hazine Avcısı");
        getContentPane().add(lblHazineAvcisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 240, 60));

        lblLevel.setForeground(new java.awt.Color(0, 0, 0));
        lblLevel.setText("Level : ");
        getContentPane().add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 50, -1));

        lblLEVEL.setText("jlabel1");
        getContentPane().add(lblLEVEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, 16));

        lblIsim.setForeground(new java.awt.Color(0, 0, 0));
        lblIsim.setText("İsim : ");
        getContentPane().add(lblIsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 40, -1));

        lblISIM.setForeground(new java.awt.Color(0, 0, 0));
        lblISIM.setText("jLabel1");
        getContentPane().add(lblISIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 60, -1));

        lblZar.setForeground(new java.awt.Color(0, 0, 0));
        lblZar.setText("Zar :");
        getContentPane().add(lblZar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 40, -1));

        lblZAR.setForeground(new java.awt.Color(0, 0, 0));
        lblZAR.setText("jLabel1");
        getContentPane().add(lblZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 60, -1));

        lblPuan.setForeground(new java.awt.Color(0, 0, 0));
        lblPuan.setText("Puan :");
        getContentPane().add(lblPuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 39, -1));

        lblPUAN.setForeground(new java.awt.Color(0, 0, 0));
        lblPUAN.setText("jLabel1");
        getContentPane().add(lblPUAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 50, -1));

        lblHazine.setForeground(new java.awt.Color(0, 0, 0));
        lblHazine.setText("Hazine :");
        getContentPane().add(lblHazine, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, -1, -1));

        lblHAZINE.setForeground(new java.awt.Color(0, 0, 0));
        lblHAZINE.setText("jLabel2");
        getContentPane().add(lblHAZINE, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 224, -1));

        lblKonum.setForeground(new java.awt.Color(0, 0, 0));
        lblKonum.setText("Konum :");
        getContentPane().add(lblKonum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, -1, -1));

        lblKONUM.setForeground(new java.awt.Color(0, 0, 0));
        lblKONUM.setText("jLabel1");
        getContentPane().add(lblKONUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 70, -1));

        btnZarAt.setBackground(new java.awt.Color(204, 204, 204));
        btnZarAt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnZarAt.setForeground(new java.awt.Color(0, 0, 0));
        btnZarAt.setText("Zar AT");
        btnZarAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZarAtActionPerformed(evt);
            }
        });
        getContentPane().add(btnZarAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aydinsandikcimenu/map.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 840, 560));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 610));

        lbl31.setBackground(new java.awt.Color(0, 0, 0));
        lbl31.setForeground(new java.awt.Color(0, 0, 0));
        lbl31.setText("1");
        lbl31.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl31, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        lbl32.setForeground(new java.awt.Color(0, 0, 0));
        lbl32.setText("1");
        lbl32.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        lbl33.setForeground(new java.awt.Color(0, 0, 0));
        lbl33.setText("1");
        lbl33.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl33, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        lbl34.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        lbl34.setForeground(new java.awt.Color(0, 0, 0));
        lbl34.setText("1");
        lbl34.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        lbl35.setBackground(new java.awt.Color(0, 0, 0));
        lbl35.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl35.setForeground(new java.awt.Color(0, 0, 0));
        lbl35.setText("1");
        lbl35.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        lbl36.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl36.setForeground(new java.awt.Color(0, 0, 0));
        lbl36.setText("1");
        lbl36.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        lbl37.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl37.setForeground(new java.awt.Color(0, 0, 0));
        lbl37.setText("1");
        lbl37.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(lbl37, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZarAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZarAtActionPerformed
        gm.zarAt();
        //if (gm.bitisEkrani() == false) {
            lblZAR.setText(gm.getZar() + "");
            lblPUAN.setText(gm.getPuan() + "");
            lblKONUM.setText(gm.getKonum() + "");
            lblHAZINE.setText(gm.getHazine() + "");
        //} else
        if (gm.bitisEkrani() == true) {
            this.dispose();
        }
    }//GEN-LAST:event_btnZarAtActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AydinSandikciIkinciEtap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AydinSandikciIkinciEtap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AydinSandikciIkinciEtap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AydinSandikciIkinciEtap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AydinSandikciIkinciEtap().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZarAt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl26;
    private javax.swing.JLabel lbl27;
    private javax.swing.JLabel lbl28;
    private javax.swing.JLabel lbl29;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl30;
    private javax.swing.JLabel lbl31;
    private javax.swing.JLabel lbl32;
    private javax.swing.JLabel lbl33;
    private javax.swing.JLabel lbl34;
    private javax.swing.JLabel lbl35;
    private javax.swing.JLabel lbl36;
    private javax.swing.JLabel lbl37;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblBitis;
    private javax.swing.JLabel lblHAZINE;
    private javax.swing.JLabel lblHazine;
    private javax.swing.JLabel lblHazineAvcisi;
    private javax.swing.JLabel lblISIM;
    private javax.swing.JLabel lblIsim;
    private javax.swing.JLabel lblKONUM;
    private javax.swing.JLabel lblKonum;
    private javax.swing.JLabel lblLEVEL;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblPUAN;
    private javax.swing.JLabel lblPuan;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblZAR;
    private javax.swing.JLabel lblZar;
    // End of variables declaration//GEN-END:variables
}
