/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aydinsandikcimenu;

/**
 *
 * @author aydin
 */
public class AydinSandikciNickName extends javax.swing.JFrame {

    /**
     * Creates new form AydinSandikciNickName
     */
    int konum = 0;
    GameManager gm = new GameManager();

    public AydinSandikciNickName(int a) {
        initComponents();
        konum = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGirilenIsim = new javax.swing.JTextField();
        btnBasla = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGirilenIsim.setToolTipText("");
        txtGirilenIsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGirilenIsimActionPerformed(evt);
            }
        });
        getContentPane().add(txtGirilenIsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 220, 30));

        btnBasla.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnBasla.setForeground(new java.awt.Color(0, 0, 0));
        btnBasla.setText("Başla");
        btnBasla.setContentAreaFilled(false);
        btnBasla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaslaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBasla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 140, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Scoreboard");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 180, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aydinsandikcimenu/giris.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtGirilenIsim.getText().trim().length() > 0) {
                this.dispose();
                AydinSandikciScoreBoard sb = new AydinSandikciScoreBoard(txtGirilenIsim.getText().trim());
                sb.setVisible(true);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBaslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaslaActionPerformed
              
            if (txtGirilenIsim.getText().trim().length() > 0) {
                this.dispose();
                AydinSandikciIlkEtap ie = new AydinSandikciIlkEtap(txtGirilenIsim.getText().trim());
                ie.setVisible(true);
            }
       


    }//GEN-LAST:event_btnBaslaActionPerformed

    private void txtGirilenIsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGirilenIsimActionPerformed

      txtGirilenIsim.setBackground(new java.awt.Color(0, 0, 0, 0));
    }//GEN-LAST:event_txtGirilenIsimActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AydinSandikciNickName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AydinSandikciNickName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AydinSandikciNickName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AydinSandikciNickName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AydinSandikciNickName().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBasla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtGirilenIsim;
    // End of variables declaration//GEN-END:variables
}
